# Generated by Django 5.2.13 on 2026-04-10 07:16

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTimeRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("clock_in", models.TimeField(blank=True, null=True)),
                ("clock_out", models.TimeField(blank=True, null=True)),
                ("break_start", models.TimeField(blank=True, null=True)),
                ("break_end", models.TimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Working"),
                            ("on_break", "On break"),
                            ("clocked_out", "Clocked out"),
                            ("incomplete", "Incomplete"),
                        ],
                        default="working",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="CorrectionRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("proposed_clock_out", models.TimeField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed", models.BooleanField(default=False)),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="corrections",
                        to="timetracking.dailytimerecord",
                    ),
                ),
            ],
            options={
                "ordering": ["-submitted_at"],
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("department", models.CharField(max_length=100)),
                (
                    "target_hours",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("160.00"), max_digits=6
                    ),
                ),
                ("pin", models.CharField(default="1234", max_length=4)),
                (
                    "role",
                    models.CharField(
                        choices=[("employee", "Employee"), ("hr", "HR")],
                        default="employee",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user__first_name", "user__last_name"],
            },
        ),
        migrations.AddField(
            model_name="dailytimerecord",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="timetracking.employee",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="dailytimerecord",
            unique_together={("employee", "date")},
        ),
        migrations.CreateModel(
            name="HRReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.IntegerField()),
                ("year", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reminder_sent", "Reminder sent"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("reminder_message", models.TextField(blank=True)),
                ("reminder_seen", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="timetracking.employee",
                    ),
                ),
            ],
            options={
                "unique_together": {("employee", "year", "month")},
            },
        ),
    ]
